ALTER SESSION SET "_ORACLE_SCRIPT"=true;

CREATE USER DB_SINESPCT IDENTIFIED BY DB_SINESPCT;

CREATE  TABLE DB_SINESPCT.CADASTRO_NACIONAL_ENDERECO ( 
	ID_CADASTRO_NACIONAL_ENDERECO INTEGER   NOT NULL,
	ED_LOGRADOURO        VARCHAR2(200)   ,
	ED_COMPLEMENTO       VARCHAR2(200)   ,
	ED_BAIRRO            VARCHAR2(100)   ,
	ED_NUMERO            VARCHAR2(20)   ,
	NR_CEP               NUMBER(8)   ,
	ID_MUNICIPIO         NUMBER(19)   NOT NULL,
	ID_CADASTRO_NACIONAL INTEGER   NOT NULL,
	CONSTRAINT PK_CADASTRO_NAC_0 PRIMARY KEY ( ID_CADASTRO_NACIONAL_ENDERECO ) ,
	CONSTRAINT UNQ_CADASTRO_NAC_ID_MUNICIPIO UNIQUE ( ID_MUNICIPIO ) ,
	CONSTRAINT UNQ_CADASTRO_NAC_ID_CADASTRO UNIQUE ( ID_CADASTRO_NACIONAL ) 
 );

CREATE  TABLE DB_SINESPCT.CADASTRO_NACIONAL_MAPA_DE_VAGAS ( 
	ID_CADASTRO_NACIONAL_MAPA_DE_VAGAS INTEGER   NOT NULL,
	ID_CADASTRO_NACIONAL INTEGER   NOT NULL,
	ID_CADASTRO_NACIONAL_TIPO_FINANCIAMENTO INTEGER   NOT NULL,
	NR_DISPONIBILIDADE   INTEGER   ,
	NR_PUBLICO           INTEGER   ,
	CONSTRAINT PK_CADASTRO_NAC_6 PRIMARY KEY ( ID_CADASTRO_NACIONAL_MAPA_DE_VAGAS ) ,
	CONSTRAINT UNQ_CADASTRO_NAC_ID_CADASTRO_4 UNIQUE ( ID_CADASTRO_NACIONAL ) ,
	CONSTRAINT UNQ_CADASTRO_NAC_ID_CADASTRO_5 UNIQUE ( ID_CADASTRO_NACIONAL_TIPO_FINANCIAMENTO ) 
 );

CREATE  TABLE DB_SINESPCT.CADASTRO_NACIONAL_REPRESENTANTE_LEGAL ( 
	ID_CADASTRO_NACIONAL_REPRESENTANTE_LEGAL INTEGER   NOT NULL,
	NO_NOME              VARCHAR2(200)   NOT NULL,
	DT_TERMINO_MANDATO   DATE   ,
	TP_PAPEL_DIRETORIA   INTEGER   NOT NULL,
	DT_NASCIMENTO        DATE   ,
	CO_CPF               CHAR(11)   NOT NULL,
	CO_TELEFONE          VARCHAR2(100)   ,
	NO_EMAIL             VARCHAR2(100)   NOT NULL,
	TP_ESCOLARIDADE      INTEGER   ,
	CO_CURSO             VARCHAR2(20)   ,
	ID_CADASTRO_NACIONAL INTEGER   NOT NULL,
	DS_PAPEL_DIRETORIA   VARCHAR2(200)   ,
	ID_CADASTRO_NACIONAL_PROFISSAO INTEGER   NOT NULL,
	CONSTRAINT PK_CN_REPRESENT PRIMARY KEY ( ID_CADASTRO_NACIONAL_REPRESENTANTE_LEGAL ) ,
	CONSTRAINT UNQ_CN_REPRESENT_ID_CADASTRO UNIQUE ( ID_CADASTRO_NACIONAL ) ,
	CONSTRAINT UNQ_CADASTRO_NAC_ID_CADASTRO_7 UNIQUE ( ID_CADASTRO_NACIONAL_PROFISSAO ) 
 );

CREATE  TABLE DB_SINESPCT.CADASTRO_NACIONAL_REPRESENTANTE_TECNICO ( 
	ID_CADASTRO_NACIONAL_REPRESENTANTE_TECNICO INTEGER   NOT NULL,
	NO_NOME              VARCHAR2(100)   NOT NULL,
	DT_NASCIMENTO        DATE   NOT NULL,
	CO_CPF               NUMBER(11)   NOT NULL,
	CO_TELEFONE          VARCHAR2(50)   NOT NULL,
	NO_EMAIL             VARCHAR2(50)   NOT NULL,
	TP_ESCOLARIDADE      INTEGER   NOT NULL,
	CO_CURSO             INTEGER   NOT NULL,
	TP_POSSUI_EXPERIENCIA INTEGER   NOT NULL,
	ID_RESPONSAVEL_PRINCIPAL INTEGER   ,
	ID_CADASTRO_NACIONAL INTEGER   NOT NULL,
	ID_CADASTRO_NACIONAL_PROFISSAO INTEGER   NOT NULL,
	CONSTRAINT PK_CADASTRO_NAC_2 PRIMARY KEY ( ID_CADASTRO_NACIONAL_REPRESENTANTE_TECNICO ) ,
	CONSTRAINT UNQ_CADASTRO_NAC_ID_CADASTRO_1 UNIQUE ( ID_CADASTRO_NACIONAL ) ,
	CONSTRAINT UNQ_CADASTRO_NAC_ID_CADASTRO_8 UNIQUE ( ID_CADASTRO_NACIONAL_PROFISSAO ) 
 );

CREATE  TABLE DB_SINESPCT.CADASTRO_NACIONAL_TIPO_FINANCIAMENTO ( 
	ID_CADASTRO_NACIONAL_TIPO_FINANCIAMENTO INTEGER   NOT NULL,
	CO_TIPO              INTEGER   ,
	ID_CADASTRO_NACIONAL INTEGER   NOT NULL,
	CO_CLASSIFICACAO     INTEGER   ,
	CONSTRAINT PK_CADASTRO_NAC_10 PRIMARY KEY ( ID_CADASTRO_NACIONAL_TIPO_FINANCIAMENTO ) ,
	CONSTRAINT UNQ_CADASTRO_NAC_ID_CADASTRO_9 UNIQUE ( ID_CADASTRO_NACIONAL ) 
 );

CREATE  TABLE DB_SINESPCT.MUNICIPIO ( 
	ID_MUNICIPIO         NUMBER(19)   NOT NULL,
	CO_MUNICIPIO         NUMBER(10)   ,
	NO_MUNICIPIO         VARCHAR2(50)   ,
	ID_UF                NUMBER(19)   NOT NULL,
	CO_MUNICIPIO_IBGE    VARCHAR2(7)   ,
	ID_CADASTRO_NACIONAL_UF INTEGER   NOT NULL,
	CONSTRAINT UNQ_MUNICIPIO_ID_CADASTRO UNIQUE ( ID_CADASTRO_NACIONAL_UF ) 
 );

CREATE UNIQUE INDEX IX_PK_MUNICIPIO ON DB_SINESPCT.MUNICIPIO ( ID_MUNICIPIO );

CREATE  TABLE DB_SINESPCT.TBL ( 
 );

CREATE  TABLE DB_SINESPCT.CADASTRO_NACIONAL_FINANCIAMENTO_VAGAS ( 
	ID_CADASTRO_NACIONAL_FINANCIAMENTO_VAGAS INTEGER   NOT NULL,
	DS_TIPO_FINANCIAMENTO VARCHAR2(200)   ,
	CONSTRAINT PK_CADASTRO_NAC_5 PRIMARY KEY ( ID_CADASTRO_NACIONAL_FINANCIAMENTO_VAGAS ) 
 );

CREATE  TABLE DB_SINESPCT.CADASTRO_NACIONAL_PROFISSAO ( 
	ID_CADASTRO_NACIONAL_PROFISSAO INTEGER   NOT NULL,
	NO_NOME              INTEGER   NOT NULL,
	CONSTRAINT PK_CADASTRO_NAC_8 PRIMARY KEY ( ID_CADASTRO_NACIONAL_PROFISSAO ) 
 );

CREATE  TABLE DB_SINESPCT.CADASTRO_NACIONAL_UF ( 
	ID_CADASTRO_NACIONAL_UF INTEGER   NOT NULL,
	NO_SIGLA             CHAR(2)   ,
	NO_NOME              VARCHAR2(100)   ,
	CONSTRAINT PK_CADASTRO_NAC_9 PRIMARY KEY ( ID_CADASTRO_NACIONAL_UF ) 
 );

CREATE  TABLE DB_SINESPCT.CADASTRO_NACIONAL ( 
	ID_CADASTRO_NACIONAL INTEGER   NOT NULL,
	CO_CNPJ              CHAR(14)   ,
	TP_AREA_ATUACAO      INTEGER   NOT NULL,
	NR_FILIAIS           INTEGER  DEFAULT 0 NOT NULL,
	NO_NOME_FANTASIA     VARCHAR2(200)   NOT NULL,
	NO_RAZAO_SOCIAL      VARCHAR2(200)   ,
	CO_CNAE_PRINCIPAL    VARCHAR2(50)   ,
	CO_CNAE_SECUNDARIO   VARCHAR2(50)   ,
	VL_RECEITA_BRUTA     NUMBER(18,2)   NOT NULL,
	TP_MODALIDADE_FINANCIAMENTO_CONTRATO INTEGER   NOT NULL,
	CO_MODALIDADE        INTEGER   ,
	CO_MODALIDADE_OUTROS INTEGER   ,
	TP_FINANCIAMENTO_ESTADO INTEGER   NOT NULL,
	TP_FINANCIAMENTO_MUNICIPIO INTEGER   ,
	CO_FINANCIAMENTO_MUNICIPIO INTEGER   ,
	TP_OUTRAS_FONTES     INTEGER   ,
	DS_OUTRAS_FONTES     VARCHAR2(100)   ,
	VL_OUTRAS_FONTES     NUMBER(18,2)   ,
	TP_OUTRAS_FONTES_MENSALIDADE INTEGER   ,
	VL_OUTRAS_FONTES_MENSALIDADE INTEGER   ,
	DS_OUTRAS_FONTES_OUTRAS VARCHAR2(50)   ,
	DS_URL_LICENCA_SANITARIA VARCHAR2(400)   ,
	DT_VALIDADE_LICENCA_SANITARIA DATE   ,
	NR_PRAZO_PROJETO     INTEGER   NOT NULL,
	DS_URL_PROJETO_TERAPEUTICO VARCHAR2(400)   ,
	TP_POSSUI_CEBAS      INTEGER   NOT NULL,
	DT_INICIO_VALIDADE_CEBAS DATE   ,
	CO_FINANCIAMENTO_ESTADO VARCHAR2(50)   ,
	DT_FIM_VALIDADE_CEBAS DATE   ,
	DS_URL_DOCUMENTO_CEBAS VARCHAR2(400)   ,
	TP_CEBAS_DEPAD       INTEGER   ,
	NU_ANO_PROTOCOLO_CEBAS INTEGER   ,
	NU_PROTOCOLO_CEBAS   INTEGER   ,
	TP_CUMPRE_CONAD      INTEGER   ,
	NU_TOTAL_VAGAS       INTEGER   ,
	NR_CAPACIDADE_ADULTO_FEMININO INTEGER   ,
	NR_CAPACIDADE_ADULTO_MASCULINO INTEGER   ,
	NR_CAPACIDADE_MAES_NUTRIZES INTEGER   ,
	TP_POSSUI_INCRICAO_MUNICIPAL INTEGER   NOT NULL,
	TP_CONSELHO_MUNICIPAL INTEGER   ,
	TP_POSSUI_INSCRICAO_ESTADUAL INTEGER   NOT NULL,
	NO_CONSELHO_ESTADUAL VARCHAR2(200)   ,
	TP_POSSUI_RECONHECIMENTO_AUTORIDADE INTEGER   NOT NULL,
	TP_AUTORIDADE        INTEGER   ,
	NR_PUBLICO_ADULTO_FEMININO INTEGER   NOT NULL,
	NR_PUBLICO_ADULTO_MASCULINO INTEGER   NOT NULL,
	NR_PUBLICO_CRIANCAS  INTEGER   NOT NULL,
	NR_PUBLICO_IDOSOS    INTEGER   NOT NULL,
	TP_CAPACIDADE_ATENDIMENTO INTEGER   NOT NULL,
	TP_FORMA_ACESSO      INTEGER   NOT NULL,
	TP_ARTICULACAO_OUTRAS_POLITICAS INTEGER   ,
	NO_DESCRICAO_OUTRA_POLITICA NVARCHAR2(200)   ,
	TP_ESPACO            INTEGER   NOT NULL,
	TP_POSSUI_ESPACO_COLETIVO INTEGER   NOT NULL,
	TP_POSSUI_ESPACO_INDIVIDUAL INTEGER   NOT NULL,
	TP_ACOLHIMENTO_PROVISORIO INTEGER   NOT NULL,
	TP_COMUNIDADE_TERAPEUTICA INTEGER   ,
	TP_PERIODICIDADE_CAPACITACAO INTEGER   NOT NULL,
	TP_ATIVIDADE_PREVENCAO INTEGER   ,
	TP_ATIVIDADE_APOIO   INTEGER   ,
	TP_ATIVIDADE_MUTUA_AJUDA INTEGER   ,
	TP_ATIVIDADE_PSICOSSOCIAL INTEGER   ,
	TP_ATIVIDADE_RESSOCIALIZACAO INTEGER   ,
	TP_GRATUITO          INTEGER   ,
	TP_CUSTEIO_CONSUMO   INTEGER   ,
	TP_CUSTEIO_RH        INTEGER   ,
	TP_CUSTEIO_ADMINISTRATIVO INTEGER   ,
	TP_CUSTEIO_OUTROS    INTEGER   ,
	DS_CUSTEIO_OUTROS    VARCHAR2(400)   ,
	TP_APENAS_VOLUNTARIOS INTEGER   ,
	TP_ESCOLARIDADE_VOLUNTARIOS INTEGER   ,
	TP_PREVENCAO_PALESTRAS INTEGER   ,
	TP_PREVENCAO_RODAS   INTEGER   ,
	TP_PREVENCAO_OFICINAS INTEGER   ,
	TP_PREVENCAO_LUDICAS INTEGER   ,
	TP_PREVENCAO_TERAPEUTICAS INTEGER   ,
	TP_PREVENCAO_PSICOSSOCIAIS INTEGER   ,
	TP_PREVENCAO_EVENTOS INTEGER   ,
	TP_PREVENCAO_OUTRAS_ACOES INTEGER   ,
	DS_PREVENCAO_OUTRAS_ACOES INTEGER   ,
	TP_PREVENCAO_DIREITOS_SOCIAIS INTEGER   ,
	TP_PREVENCAO_FAMILIA INTEGER   ,
	TP_PREVENCAO_SAUDE_MENTAL INTEGER   ,
	TP_PREVENCAO_ALCOOL_DROGAS INTEGER   ,
	TP_PREVENCAO_ESPIRITUALIDADE INTEGER   ,
	TP_PREVENCAO_OUTROS_TEMAS INTEGER   ,
	DS_PREVENCAO_OUTROS_TEMAS INTEGER   ,
	NO_EMAIL_INSTITUCIONAL VARCHAR2(200)   ,
	TP_OUTRAS_FONTES_CAMPANHAS INTEGER   ,
	TP_OUTRAS_FONTES_DOACOES INTEGER   ,
	TP_OUTRAS_FONTES_VENDAS INTEGER   ,
	TP_PREVENCAO_PERIDIOCIDADE INTEGER   ,
	DS_PREVENCAO_PERIDIOCIDADE_OUTRA VARCHAR2(100)   ,
	TP_PREVENCAO_CONTROLE_PUBLICO INTEGER   ,
	TP_APOIO_12_PASSOS   INTEGER   ,
	DS_APOIO_METODOLOGIA VARCHAR2(200)   ,
	TP_APOIO_GRUPO_12_PASSOS INTEGER   ,
	DS_APOIO_GRUPO_12_PASSOS VARCHAR2(200)   ,
	TP_PSICOSSOCIAL      INTEGER   ,
	TP_PSICOSSOCIAL_ACOLHIMENTO INTEGER   ,
	TP_PSICOSSOCIAL_INDIVIDUAL INTEGER   ,
	TP_PSICOSSOCIAL_ENCAMINHAMENTO INTEGER   ,
	TP_PSICOSSOCIAL_OUTROS INTEGER   ,
	DS_PSICOSSOCIAL_OUTROS VARCHAR2(200)   ,
	DS_PSICOSSOCIAL_PROFISSIONAIS VARCHAR2(200)   ,
	TP_RESSOCIALIZACAO   INTEGER   ,
	TP_RESSOCIALIZACAO_CAPACITACAO INTEGER   ,
	TP_RESSOCIALIZACAO_ENCAMINHAMENTO INTEGER   ,
	TP_RESSOCIALIZACAO_VINCULOS_FAMILIARES INTEGER   ,
	TP_RESSOCIALIZACAO_OUTROS INTEGER   ,
	DS_RESSOCIALIZACAO_OUTROS VARCHAR2(200)   ,
	TP_RESSOCIALIZACAO_PARCERIAS INTEGER   ,
	TP_RESSOCIALIZACAO_PARCERIAS_INSTITUICOES INTEGER   ,
	TP_RESSOCIALIZACAO_PARCERIAS_EMPRESAS INTEGER   ,
	TP_RESSOCIALIZACAO_PARCERIAS_ORG_PUBLICO INTEGER   ,
	TP_RESSOCIALIZACAO_PARCERIAS_NAO_POSSUI INTEGER   ,
	TP_RESSOCIALIZACAO_PARCERIAS_VINCULOS INTEGER   ,
	TP_RESSOCIALIZACAO_PARCERIAS_OUTROS INTEGER   ,
	DS_RESSOCIALIZACAO_PARCERIAS_OUTROS VARCHAR2(200)   ,
	TP_SICAF             INTEGER   ,
	CONSTRAINT PK_CADASTRO_NAC PRIMARY KEY ( ID_CADASTRO_NACIONAL ) 
 );

CREATE  TABLE DB_SINESPCT.CADASTRO_NACIONAL_ARQUIVOS ( 
	ID_CADASTRO_NACIONAL_ARQUIVOS INTEGER   NOT NULL,
	DT_VALIDADE          DATE   ,
	DS_ARQUIVO_URL       VARCHAR2(400)   ,
	ID_CADASTRO_NACIONAL_TIPO_ARQUIVO INTEGER   NOT NULL,
	ID_CADASTRO_NACIONAL INTEGER   NOT NULL,
	CONSTRAINT PK_CADASTRO_NAC_3 PRIMARY KEY ( ID_CADASTRO_NACIONAL_ARQUIVOS ) ,
	CONSTRAINT UNQ_CADASTRO_NAC_ID_CADASTRO_2 UNIQUE ( ID_CADASTRO_NACIONAL_TIPO_ARQUIVO ) ,
	CONSTRAINT UNQ_CADASTRO_NAC_ID_CADASTRO_3 UNIQUE ( ID_CADASTRO_NACIONAL ) 
 );

CREATE  TABLE DB_SINESPCT.CADASTRO_NACIONAL_CONTATOS ( 
	ID_CADASTRO_NACIONAL_CONTATOS INTEGER   NOT NULL,
	NO_CONTATO           VARCHAR2(200)   NOT NULL,
	ID_CN_TIPO_CONTATO   INTEGER   NOT NULL,
	ID_CADASTRO_NACIONAL INTEGER   NOT NULL,
	CONSTRAINT PK_CADASTRO_NAC_1 PRIMARY KEY ( ID_CADASTRO_NACIONAL_CONTATOS ) ,
	CONSTRAINT UNQ_CADASTRO_NAC_ID_CN_TIPO_C UNIQUE ( ID_CN_TIPO_CONTATO ) ,
	CONSTRAINT UNQ_CADASTRO_NAC_ID_CADASTRO_0 UNIQUE ( ID_CADASTRO_NACIONAL ) 
 );

CREATE  TABLE DB_SINESPCT.CADASTRO_NACIONAL_FUNCIONARIO_TECNICO ( 
	ID_CADASTRO_NACIONAL_FUNCIONARIO_TECNICO INTEGER   NOT NULL,
	NO_NOME              NVARCHAR2(200)   NOT NULL,
	ID_PROFISSAO         INTEGER   NOT NULL,
	NR_CARGA_HORARIA     INTEGER   NOT NULL,
	TP_VINCULO           INTEGER   NOT NULL,
	ID_CADASTRO_NACIONAL INTEGER   ,
	CONSTRAINT PK_CADASTRO_NAC_7 PRIMARY KEY ( ID_CADASTRO_NACIONAL_FUNCIONARIO_TECNICO ) ,
	CONSTRAINT UNQ_CADASTRO_NAC_ID_CADASTRO_6 UNIQUE ( ID_CADASTRO_NACIONAL ) 
 );

CREATE  TABLE DB_SINESPCT.CADASTRO_NACIONAL_TIPO_ARQUIVO ( 
	ID_CADASTRO_NACIONAL_TIPO_ARQUIVO INTEGER   NOT NULL,
	DS_TIPO_ARQUIVO      VARCHAR2(100)   ,
	CO_SESSAO_FORMULARIO INTEGER   NOT NULL,
	CONSTRAINT PK_CADASTRO_NAC_4 PRIMARY KEY ( ID_CADASTRO_NACIONAL_TIPO_ARQUIVO ) 
 );

CREATE  TABLE DB_SINESPCT.CADASTRO_NACIONAL_TIPO_CONTATO ( 
	ID_CADASTRO_NACIONAL_TIPO_CONTATO INTEGER   NOT NULL,
	NO_TIPO_CONTATO      VARCHAR2(50)   ,
	CONSTRAINT PK_CN_TIPO_CONT PRIMARY KEY ( ID_CADASTRO_NACIONAL_TIPO_CONTATO ) 
 );

ALTER TABLE DB_SINESPCT.CADASTRO_NACIONAL ADD CONSTRAINT FK_CADASTRO_NACIONAL_CADASTRO_NACIONAL_ENDERECO FOREIGN KEY ( ID_CADASTRO_NACIONAL ) REFERENCES DB_SINESPCT.CADASTRO_NACIONAL_ENDERECO( ID_CADASTRO_NACIONAL );

ALTER TABLE DB_SINESPCT.CADASTRO_NACIONAL ADD CONSTRAINT FK_CADASTRO_NACIONAL_CADASTRO_NACIONAL_CONTATOS FOREIGN KEY ( ID_CADASTRO_NACIONAL ) REFERENCES DB_SINESPCT.CADASTRO_NACIONAL_CONTATOS( ID_CADASTRO_NACIONAL );

ALTER TABLE DB_SINESPCT.CADASTRO_NACIONAL ADD CONSTRAINT FK_CADASTRO_NACIONAL_CN_REPRESENTANTE_LEGAL FOREIGN KEY ( ID_CADASTRO_NACIONAL ) REFERENCES DB_SINESPCT.CADASTRO_NACIONAL_REPRESENTANTE_LEGAL( ID_CADASTRO_NACIONAL );

ALTER TABLE DB_SINESPCT.CADASTRO_NACIONAL ADD CONSTRAINT FK_CADASTRO_NACIONAL_CADASTRO_NACIONAL_REPRESENTANTE_TECNICO FOREIGN KEY ( ID_CADASTRO_NACIONAL ) REFERENCES DB_SINESPCT.CADASTRO_NACIONAL_REPRESENTANTE_TECNICO( ID_CADASTRO_NACIONAL );

ALTER TABLE DB_SINESPCT.CADASTRO_NACIONAL ADD CONSTRAINT FK_CADASTRO_NACIONAL_CADASTRO_NACIONAL_ARQUIVOS FOREIGN KEY ( ID_CADASTRO_NACIONAL ) REFERENCES DB_SINESPCT.CADASTRO_NACIONAL_ARQUIVOS( ID_CADASTRO_NACIONAL );

ALTER TABLE DB_SINESPCT.CADASTRO_NACIONAL ADD CONSTRAINT FK_CADASTRO_NACIONAL_CADASTRO_NACIONAL_MAPA_DE_VAGAS FOREIGN KEY ( ID_CADASTRO_NACIONAL ) REFERENCES DB_SINESPCT.CADASTRO_NACIONAL_MAPA_DE_VAGAS( ID_CADASTRO_NACIONAL );

ALTER TABLE DB_SINESPCT.CADASTRO_NACIONAL ADD CONSTRAINT FK_CADASTRO_NACIONAL_CADASTRO_NACIONAL_FUNCIONARIO_TECNICO FOREIGN KEY ( ID_CADASTRO_NACIONAL ) REFERENCES DB_SINESPCT.CADASTRO_NACIONAL_FUNCIONARIO_TECNICO( ID_CADASTRO_NACIONAL );

ALTER TABLE DB_SINESPCT.CADASTRO_NACIONAL ADD CONSTRAINT FK_CADASTRO_NACIONAL_CADASTRO_NACIONAL_TIPO_FINANCIAMENTO FOREIGN KEY ( ID_CADASTRO_NACIONAL ) REFERENCES DB_SINESPCT.CADASTRO_NACIONAL_TIPO_FINANCIAMENTO( ID_CADASTRO_NACIONAL );

ALTER TABLE DB_SINESPCT.CADASTRO_NACIONAL_ARQUIVOS ADD CONSTRAINT FK_CADASTRO_NACIONAL_ARQUIVOS FOREIGN KEY ( ID_CADASTRO_NACIONAL ) REFERENCES DB_SINESPCT.CADASTRO_NACIONAL( ID_CADASTRO_NACIONAL );

ALTER TABLE DB_SINESPCT.CADASTRO_NACIONAL_CONTATOS ADD CONSTRAINT FK_CADASTRO_NACIONAL_CONTATOS FOREIGN KEY ( ID_CADASTRO_NACIONAL ) REFERENCES DB_SINESPCT.CADASTRO_NACIONAL( ID_CADASTRO_NACIONAL );

ALTER TABLE DB_SINESPCT.CADASTRO_NACIONAL_FINANCIAMENTO_VAGAS ADD CONSTRAINT FK_CADASTRO_NACIONAL_TIPO_FINANCIAMENTO_CADASTRO_NACIONAL_MAPA_DE_VAGAS FOREIGN KEY ( ID_CADASTRO_NACIONAL_FINANCIAMENTO_VAGAS ) REFERENCES DB_SINESPCT.CADASTRO_NACIONAL_MAPA_DE_VAGAS( ID_CADASTRO_NACIONAL_TIPO_FINANCIAMENTO );

ALTER TABLE DB_SINESPCT.CADASTRO_NACIONAL_FUNCIONARIO_TECNICO ADD CONSTRAINT FK_CADASTRO_NACIONAL_EQUIPE_TECNICA FOREIGN KEY ( ID_CADASTRO_NACIONAL ) REFERENCES DB_SINESPCT.CADASTRO_NACIONAL( ID_CADASTRO_NACIONAL );

ALTER TABLE DB_SINESPCT.CADASTRO_NACIONAL_FUNCIONARIO_TECNICO ADD CONSTRAINT FK_CADASTRO_NACIONAL_FUNCIONARIO_TECNICO FOREIGN KEY ( ID_PROFISSAO ) REFERENCES DB_SINESPCT.CADASTRO_NACIONAL_PROFISSAO( ID_CADASTRO_NACIONAL_PROFISSAO );

ALTER TABLE DB_SINESPCT.CADASTRO_NACIONAL_PROFISSAO ADD CONSTRAINT FK_CADASTRO_NACIONAL_PROFISSAO_CADASTRO_NACIONAL_REPRESENTANTE_LEGAL FOREIGN KEY ( ID_CADASTRO_NACIONAL_PROFISSAO ) REFERENCES DB_SINESPCT.CADASTRO_NACIONAL_REPRESENTANTE_LEGAL( ID_CADASTRO_NACIONAL_PROFISSAO );

ALTER TABLE DB_SINESPCT.CADASTRO_NACIONAL_PROFISSAO ADD CONSTRAINT FK_CADASTRO_NACIONAL_PROFISSAO_CADASTRO_NACIONAL_REPRESENTANTE_TECNICO FOREIGN KEY ( ID_CADASTRO_NACIONAL_PROFISSAO ) REFERENCES DB_SINESPCT.CADASTRO_NACIONAL_REPRESENTANTE_TECNICO( ID_CADASTRO_NACIONAL_PROFISSAO );

ALTER TABLE DB_SINESPCT.CADASTRO_NACIONAL_TIPO_ARQUIVO ADD CONSTRAINT FK_CADASTRO_NACIONAL_TIPO_ARQUIVO_CADASTRO_NACIONAL_ARQUIVOS FOREIGN KEY ( ID_CADASTRO_NACIONAL_TIPO_ARQUIVO ) REFERENCES DB_SINESPCT.CADASTRO_NACIONAL_ARQUIVOS( ID_CADASTRO_NACIONAL_TIPO_ARQUIVO );

ALTER TABLE DB_SINESPCT.CADASTRO_NACIONAL_TIPO_CONTATO ADD CONSTRAINT FK_CN_TIPO_CONTATO_CADASTRO_NACIONAL_CONTATOS FOREIGN KEY ( ID_CADASTRO_NACIONAL_TIPO_CONTATO ) REFERENCES DB_SINESPCT.CADASTRO_NACIONAL_CONTATOS( ID_CN_TIPO_CONTATO );

ALTER TABLE DB_SINESPCT.CADASTRO_NACIONAL_UF ADD CONSTRAINT FK_CADASTRO_NACIONAL_UF_MUNICIPIO FOREIGN KEY ( ID_CADASTRO_NACIONAL_UF ) REFERENCES DB_SINESPCT.MUNICIPIO( ID_CADASTRO_NACIONAL_UF );

ALTER TABLE DB_SINESPCT.MUNICIPIO ADD CONSTRAINT FK_MUNICIPIO_CADASTRO_NACIONAL_ENDERECO FOREIGN KEY ( ID_MUNICIPIO ) REFERENCES DB_SINESPCT.CADASTRO_NACIONAL_ENDERECO( ID_MUNICIPIO );

COMMENT ON COLUMN DB_SINESPCT.CADASTRO_NACIONAL_ENDERECO.ID_MUNICIPIO IS 'Identificador do Município no sistema.';

COMMENT ON TABLE DB_SINESPCT.MUNICIPIO IS 'Representa as informações de um Município no sistema.';

COMMENT ON COLUMN DB_SINESPCT.MUNICIPIO.ID_MUNICIPIO IS 'Identificador do Município no sistema.';

COMMENT ON COLUMN DB_SINESPCT.MUNICIPIO.CO_MUNICIPIO IS 'Código do município de acordo com a TOM (Tabela de Municípios).';

COMMENT ON COLUMN DB_SINESPCT.MUNICIPIO.NO_MUNICIPIO IS 'Nome do Município de acordo com a TOM (Tabela de Municípios).';

COMMENT ON COLUMN DB_SINESPCT.MUNICIPIO.ID_UF IS 'Identificador da UF (Estado) do Município.';

